name: Crunchy containers

on:
  push:
  pull_request:
  schedule:
    - cron: '0 6 * * *'  # Daily 6AM UTC build

env:
  CCP_BASEOS: rocky8
  CCP_PGVERSION: 14
  CCP_PG_FULLVERSION: 14.5
  CCP_VERSION: 5.1.2-0
  CCP_IMAGE_PREFIX: jelmer-crunchy
  CCP_POSTGIS_VERSION: 3.2
  CCP_SECURITY_CONTEXT: ""
  CCP_CLI: kubectl
  CCP_NAMESPACE: postgres-operator
  CCP_PG_EXTENSIONS: ""
  CCP_BACKREST_VERSION: 2.36
  CCP_PGADMIN_VERSION: 4.20

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v3
    - name: Install native dependencies
      run: sudo apt-get update && sudo apt-get satisfy -y buildah git wget
    - name: Setup
      env:
        CCPROOT: "${{ github.workspace }}"
      run: make setup
    - name: Fetch repositories
      env:
        CCPROOT: "${{ github.workspace }}"
      run: |
        wget https://api.developers.crunchydata.com/downloads/repo/rpm-centos/postgresql14/crunchypg14.repo -O "$CCPROOT/conf/crunchypg14.repo"
        wget https://api.developers.crunchydata.com/downloads/gpg/RPM-GPG-KEY-crunchydata-dev -O "$CCPROOT/conf/RPM-GPG-KEY-crunchydata-dev"
    - name: Build all images
      env:
        CCP_IMAGE_TAG: "${{ env.CCP_BASEOS }}-${{ env.CCP_PG_FULLVERSION }}-${{ env.CCP_VERSION }}"
        CCPROOT: "${{ github.workspace }}"
        CCP_POSTGIS_IMAGE_TAG: "${{ env.CCP_BASEOS }}-${{ env.CCP_PG_FULLVERSION }}-${{ env.CCP_POSTGIS_VERSION }}-${{ env.CCP_VERSION }}"
      run: make all
